use crate::{
    context::TransactionContext,
    executor::threadpool,
    meta::{MetadataManager, OpenMetadataError},
    metrics::DatabaseMetrics,
    page::{PageError, PageId, PageManager},
    storage::engine::{self, StorageEngine},
    transaction::{Transaction, TransactionError, TransactionManager, RO, RW},
};
use alloy_primitives::B256;
use parking_lot::Mutex;
use rayon::ThreadPoolBuildError;
use std::{
    fs::File,
    io,
    num::NonZero,
    ops::Deref,
    path::{Path, PathBuf},
};

#[derive(Debug)]
pub struct Database {
    pub(crate) storage_engine: StorageEngine,
    pub(crate) transaction_manager: Mutex<TransactionManager>,
    metrics: DatabaseMetrics,
}

#[must_use]
#[derive(Default, Debug)]
pub struct DatabaseOptions {
    create: bool,
    create_new: bool,
    wipe: bool,
    meta_path: Option<PathBuf>,
    max_pages: Option<NonZero<u32>>,
    num_threads: Option<NonZero<usize>>,
}

#[derive(Debug)]
pub enum Error {
    PageError(PageError),
    EngineError(engine::Error),
}

#[derive(Debug)]
pub enum OpenError {
    PageError(PageError),
    MetadataError(OpenMetadataError),
    ThreadPoolError(ThreadPoolBuildError),
    IO(io::Error),
}

impl DatabaseOptions {
    /// Sets the option to create a new database, or open it if it already exists.
    ///
    /// The semantics of this method are equivalent to [`std::fs::OpenOptions::create()`].
    pub fn create(&mut self, create: bool) -> &mut Self {
        self.create = create;
        self
    }

    /// Sets the option to create a new database, failing if it already exists.
    ///
    /// The semantics of this method are equivalent to [`std::fs::OpenOptions::create_new()`].
    ///
    /// If `create_new(true)` is set, then [`create()`](Self::create) and [`wipe()`](Self::wipe)
    /// are ignored.
    pub fn create_new(&mut self, create_new: bool) -> &mut Self {
        self.create_new = create_new;
        self
    }

    /// Sets the option to erase the database if it gets successfully opened.
    pub fn wipe(&mut self, wipe: bool) -> &mut Self {
        self.wipe = wipe;
        self
    }

    /// Specifies the path of the metadata file.
    ///
    /// By default, the metadata file path is generated by appending `".meta"` to the database file
    /// path.
    pub fn meta_path(&mut self, meta_path: impl Into<PathBuf>) -> &mut Self {
        self.meta_path = Some(meta_path.into());
        self
    }

    /// Sets the maximum number of pages that can be allocated.
    pub fn max_pages(&mut self, max_pages: NonZero<u32>) -> &mut Self {
        self.max_pages = Some(max_pages);
        self
    }

    /// Sets the maximum number of threads used to CPU-intensive computations (like hashing).
    ///
    /// By default, the number of threads is selected automatically based on the number of
    /// available CPUs on the system. The algorithm for deciding the default number is not
    /// specified and may change in the future.
    pub fn num_threads(&mut self, num_threads: NonZero<usize>) -> &mut Self {
        self.num_threads = Some(num_threads);
        self
    }

    /// Opens the database file at the given path.
    pub fn open(&self, db_path: impl AsRef<Path>) -> Result<Database, OpenError> {
        let db_path = db_path.as_ref();
        let meta_path = self.meta_path.clone().unwrap_or_else(|| {
            let mut meta_path = db_path.to_path_buf();
            meta_path.as_mut_os_string().push(".meta");
            meta_path
        });

        Database::open_with_options(db_path, meta_path, self)
    }
}

impl Database {
    pub fn open(db_path: impl AsRef<Path>) -> Result<Self, OpenError> {
        Self::options().open(db_path)
    }

    pub fn create_new(db_path: impl AsRef<Path>) -> Result<Self, OpenError> {
        Self::options().create_new(true).open(db_path)
    }

    pub fn options() -> DatabaseOptions {
        DatabaseOptions::default()
    }

    fn open_with_options(
        db_path: impl AsRef<Path>,
        meta_path: impl AsRef<Path>,
        opts: &DatabaseOptions,
    ) -> Result<Self, OpenError> {
        let db_path = db_path.as_ref();
        let meta_path = meta_path.as_ref();

        let meta_file = File::options()
            .read(true)
            .write(true)
            .create(opts.create)
            .create_new(opts.create_new)
            .truncate(false)
            .open(meta_path)
            .map_err(OpenError::IO)?;
        let mut meta_manager =
            MetadataManager::from_file(meta_file).map_err(OpenError::MetadataError)?;

        if opts.wipe {
            meta_manager.wipe().map_err(OpenError::IO)?
        }

        let page_count = meta_manager.active_slot().page_count();

        let mut page_manager_options = PageManager::options();
        page_manager_options
            .create(opts.create)
            .create_new(opts.create_new)
            .wipe(opts.wipe)
            .page_count(page_count);
        if let Some(max_pages) = opts.max_pages {
            page_manager_options.max_pages(max_pages.get());
        }

        let page_manager = page_manager_options.open(db_path).map_err(OpenError::PageError)?;

        let thread_pool = threadpool::builder()
            .num_threads(opts.num_threads.map(NonZero::get).unwrap_or(0))
            .build()
            .map_err(OpenError::ThreadPoolError)?;

        Ok(Self::new(StorageEngine::new(page_manager, meta_manager, thread_pool)))
    }

    pub fn new(storage_engine: StorageEngine) -> Self {
        Self {
            storage_engine,
            transaction_manager: Mutex::new(TransactionManager::new()),
            metrics: DatabaseMetrics::default(),
        }
    }

    pub fn close(self) -> io::Result<()> {
        self.storage_engine.close()
    }

    pub fn print_page(&self, buf: impl io::Write, page_id: Option<PageId>) -> Result<(), Error> {
        let context = self.storage_engine.read_context();
        self.storage_engine
            .debugger()
            .print_page(&context, buf, page_id)
            .map_err(Error::EngineError)
    }

    pub fn root_page_info(
        &self,
        buf: impl io::Write,
        file_path: impl AsRef<Path>,
    ) -> Result<(), OpenError> {
        self.storage_engine.debugger().root_page_info(buf, file_path).map_err(|e| match e {
            engine::Error::IO(io_err) => OpenError::IO(io_err),
            engine::Error::PageError(page_err) => OpenError::PageError(page_err),
            _ => OpenError::IO(io::Error::other("Root page info failed")),
        })
    }

    pub fn print_statistics(&self, buf: impl io::Write) -> Result<(), Error> {
        let context = self.storage_engine.read_context();
        self.storage_engine.debugger().debug_statistics(&context, buf).map_err(Error::EngineError)
    }

    pub fn consistency_check(
        &self,
        buf: impl io::Write,
        file_path: impl AsRef<Path>,
    ) -> Result<(), OpenError> {
        self.storage_engine
            .debugger()
            .database_consistency_check(buf, file_path, &self.storage_engine)
            .map_err(|e| match e {
                engine::Error::IO(io_err) => OpenError::IO(io_err),
                engine::Error::PageError(page_err) => OpenError::PageError(page_err),
                _ => OpenError::IO(io::Error::other("Consistency check failed")),
            })
    }

    pub fn begin_ro(&self) -> Result<Transaction<&Self, RO>, TransactionError> {
        begin_ro(self)
    }

    pub fn begin_rw(&self) -> Result<Transaction<&Self, RW>, TransactionError> {
        begin_rw(self)
    }

    pub fn state_root(&self) -> B256 {
        self.storage_engine.read_context().root_node_hash
    }

    pub fn size(&self) -> u32 {
        self.storage_engine.size()
    }

    pub fn update_metrics_ro(&self, context: &TransactionContext) {
        self.metrics
            .ro_transaction_pages_read
            .record(context.transaction_metrics.take_pages_read() as f64);

        let (cache_storage_read_hit, cache_storage_read_miss) =
            context.transaction_metrics.take_cache_storage_read();
        self.metrics.cache_storage_read_hit.increment(cache_storage_read_hit as u64);
        self.metrics.cache_storage_read_miss.increment(cache_storage_read_miss as u64);
    }

    pub fn update_metrics_rw(&self, context: &TransactionContext) {
        self.metrics
            .rw_transaction_pages_read
            .record(context.transaction_metrics.take_pages_read() as f64);
        self.metrics
            .rw_transaction_pages_allocated
            .record(context.transaction_metrics.take_pages_allocated() as f64);
        self.metrics
            .rw_transaction_pages_reallocated
            .record(context.transaction_metrics.take_pages_reallocated() as f64);
        self.metrics
            .rw_transaction_pages_split
            .record(context.transaction_metrics.take_pages_split() as f64);
    }
}

pub fn begin_ro<DB: Deref<Target = Database>>(
    db: DB,
) -> Result<Transaction<DB, RO>, TransactionError> {
    let context = db.storage_engine.read_context();
    db.transaction_manager.lock().begin_ro(context.snapshot_id);
    Ok(Transaction::new(context, db))
}

pub fn begin_rw<DB: Deref<Target = Database>>(
    db: DB,
) -> Result<Transaction<DB, RW>, TransactionError> {
    let context = db.storage_engine.write_context();
    let min_snapshot_id = db.transaction_manager.lock().begin_rw(context.snapshot_id)?;
    if min_snapshot_id > 0 {
        db.storage_engine.unlock(min_snapshot_id - 1);
    }
    Ok(Transaction::new(context, db))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{account::Account, path::AddressPath};
    use alloy_primitives::{address, Address, U256};
    use alloy_trie::{EMPTY_ROOT_HASH, KECCAK_EMPTY};
    use std::{fs, sync::Arc};
    use tempdir::TempDir;

    #[test]
    fn test_open() {
        let tmp_dir = TempDir::new("test_db").expect("temporary dir creation failed");
        let db_path = tmp_dir.path().join("db-file");
        let auto_meta_path = tmp_dir.path().join("db-file.meta");
        let custom_meta_path = tmp_dir.path().join("meta-file");

        // Try to open a non-existing database
        Database::options()
            .open(&db_path)
            .expect_err("opening a non-existing database should have failed");
        assert!(!db_path.exists());
        assert!(!auto_meta_path.exists());

        // Open with create(true)
        Database::options()
            .create(true)
            .open(&db_path)
            .expect("database creation should have succeeded");
        assert!(db_path.exists());
        assert!(auto_meta_path.exists());

        // Open again with create_new(true)
        Database::options()
            .create_new(true)
            .open(&db_path)
            .expect_err("database creation should have failed");
        assert!(db_path.exists());
        assert!(auto_meta_path.exists());

        // Remove the files and open with create_new(true)
        fs::remove_file(&db_path).expect("database file removal failed");
        fs::remove_file(&auto_meta_path).expect("metadata file removal failed");
        Database::options()
            .create_new(true)
            .open(&db_path)
            .expect("database creation should have succeeded");
        assert!(db_path.exists());
        assert!(auto_meta_path.exists());

        // Remove all files, and open with a custom metadata path
        fs::remove_file(&db_path).expect("database file removal failed");
        fs::remove_file(&auto_meta_path).expect("metadata file removal failed");
        Database::options()
            .create(true)
            .meta_path(&custom_meta_path)
            .open(&db_path)
            .expect("database creation should have succeeded");
        assert!(db_path.exists());
        assert!(custom_meta_path.exists());
        assert!(!auto_meta_path.exists());
    }

    #[test]
    fn test_wipe() {
        let tmp_dir = TempDir::new("test_db").expect("temporary dir creation failed");
        let db_path = tmp_dir.path().join("db-file");

        let address = address!("0xd8da6bf26964af9d7eed9e03e53415d37aa96045");

        // First create a new database and put some records in it
        {
            let db = Database::create_new(&db_path).expect("creating a new database failed");
            let account1 = Account::new(1, U256::from(100), EMPTY_ROOT_HASH, KECCAK_EMPTY);
            let mut tx = db.begin_rw().expect("creating read/write transaction failed");
            tx.set_account(AddressPath::for_address(address), Some(account1.clone())).unwrap();
            tx.commit().expect("commit failed");
        }

        // Verify that the database exists, and contains some data
        {
            let db = Database::open(&db_path).expect("opening an existing database failed");
            let mut tx = db.begin_ro().expect("creating read transaction failed");
            assert!(tx
                .get_account(&AddressPath::for_address(address))
                .expect("retrieving account failed")
                .is_some());
        }

        // Now open with `wipe(true)`, and verify that the contents are gone
        {
            let db = Database::options()
                .wipe(true)
                .open(&db_path)
                .expect("opening an existing database failed");
            let mut tx = db.begin_ro().expect("creating read transaction failed");
            assert!(tx
                .get_account(&AddressPath::for_address(address))
                .expect("retrieving account failed")
                .is_none());
        }
    }

    #[test]
    fn test_set_get_account() {
        let tmp_dir = TempDir::new("test_db").unwrap();
        let file_path = tmp_dir.path().join("test.db");
        let db = Database::create_new(file_path).unwrap();

        let address = address!("0xd8da6bf26964af9d7eed9e03e53415d37aa96045");

        let account1 = Account::new(1, U256::from(100), EMPTY_ROOT_HASH, KECCAK_EMPTY);
        let mut tx = begin_rw(&db).unwrap();
        tx.set_account(AddressPath::for_address(address), Some(account1.clone())).unwrap();

        tx.commit().unwrap();

        let account2 = Account::new(456, U256::from(123), EMPTY_ROOT_HASH, KECCAK_EMPTY);
        let mut tx = begin_rw(&db).unwrap();
        tx.set_account(AddressPath::for_address(address), Some(account2.clone())).unwrap();

        let mut ro_tx = db.begin_ro().unwrap();
        tx.commit().unwrap();

        // The read transaction was created before the write was committed, so it should not see the
        // changes.
        let read_account = ro_tx.get_account(&AddressPath::for_address(address)).unwrap();

        assert_eq!(account1, read_account.unwrap());

        // The writer transaction is committed, so the read transaction should see the changes.
        let mut ro_tx = db.begin_ro().unwrap();

        let read_account = ro_tx.get_account(&AddressPath::for_address(address)).unwrap();

        assert_eq!(account2, read_account.unwrap());

        // cleanup
        tmp_dir.close().unwrap();
    }

    #[test]
    fn test_open_resize() {
        // GIVEN: a database
        //
        // create the database on disk. currently this will create a database with 0 pages
        let tmp_dir = TempDir::new("test_db").unwrap();
        let file_path = tmp_dir.path().join("test.db");
        let _db = Database::create_new(&file_path).unwrap();

        // WHEN: the database is opened
        let db = Database::open(&file_path).unwrap();

        // THEN: the size of the database should be 0
        assert_eq!(db.size(), 0);

        // cleanup
        tmp_dir.close().unwrap();
    }

    #[test]
    fn test_data_persistence() {
        let tmp_dir = TempDir::new("test_db").unwrap();
        let file_path = tmp_dir.path().join("test.db");
        let db = Database::create_new(&file_path).unwrap();

        let address1 = address!("0xd8da6bf26964af9d7eed9e03e53415d37aa96045");
        let account1 = Account::new(1, U256::from(100), EMPTY_ROOT_HASH, KECCAK_EMPTY);

        let mut tx = db.begin_rw().unwrap();
        tx.set_account(AddressPath::for_address(address1), Some(account1.clone())).unwrap();

        tx.commit().unwrap();
        db.close().unwrap();

        let db = Database::open(&file_path).unwrap();
        let mut tx = db.begin_ro().unwrap();
        let account = tx.get_account(&AddressPath::for_address(address1)).unwrap().unwrap();
        assert_eq!(account, account1);

        tx.commit().unwrap();

        let address2 = address!("0x1234567890abcdef1234567890abcdef12345678");
        let account2 = Account::new(2, U256::from(200), EMPTY_ROOT_HASH, KECCAK_EMPTY);
        let mut tx = db.begin_rw().unwrap();
        tx.set_account(AddressPath::for_address(address2), Some(account2.clone())).unwrap();

        tx.commit().unwrap();
        db.close().unwrap();

        let db = Database::open(&file_path).unwrap();
        let mut tx = db.begin_ro().unwrap();

        let account = tx.get_account(&AddressPath::for_address(address1)).unwrap().unwrap();
        assert_eq!(account, account1);

        let account = tx.get_account(&AddressPath::for_address(address2)).unwrap().unwrap();
        assert_eq!(account, account2);
    }

    #[test]
    fn test_orphan_page_recycling_safety() {
        fn random_accounts(count: usize) -> impl Iterator<Item = (AddressPath, Option<Account>)> {
            (0..count).map(|_| {
                let address = Address::random();
                let account = Account::new(1, U256::from(100), EMPTY_ROOT_HASH, KECCAK_EMPTY);
                (AddressPath::for_address(address), Some(account))
            })
        }

        fn alive_page_ids(db: &Database) -> Vec<PageId> {
            let orphan_pages = db
                .storage_engine
                .meta_manager
                .lock()
                .orphan_pages()
                .iter()
                .map(|orphan| orphan.page_id())
                .collect::<Vec<_>>();
            let all_pages = (1..=db.storage_engine.page_manager.size())
                .map(|page_id| PageId::new(page_id).unwrap());
            all_pages.filter(move |page_id| !orphan_pages.contains(page_id)).collect()
        }

        // Create a new database and verify it has no pages
        let tmp_dir = TempDir::new("test_db").unwrap();
        let file_path = tmp_dir.path().join("test.db");
        let db = Database::create_new(file_path).unwrap();
        assert_eq!(db.storage_engine.page_manager.size(), 0);

        // Add 1000 accounts
        let mut tx = db.begin_rw().expect("rw transaction creation failed");
        let initial_accounts = random_accounts(1000).collect::<Vec<_>>();
        for (address, account) in &initial_accounts {
            tx.set_account(address.clone(), account.clone()).expect("adding account failed");
        }
        tx.commit().expect("commit failed");

        // Verify that the 1000 accounts got recorded in more than 1 page at snapshot 1
        let page_ids = alive_page_ids(&db);
        assert!(page_ids.len() > 1, "storage has no pages");
        for page_id in &page_ids {
            assert_eq!(
                db.storage_engine
                    .page_manager
                    .get(1, *page_id)
                    .unwrap_or_else(|err| panic!("page {page_id} not found: {err:?}"))
                    .snapshot_id(),
                1
            );
        }

        // Add 1000 more accounts
        let mut tx = db.begin_rw().expect("rw transaction creation failed");
        let more_accounts = random_accounts(1000).collect::<Vec<_>>();
        for (address, account) in &more_accounts {
            tx.set_account(address.clone(), account.clone()).expect("adding account failed");
        }
        tx.commit().expect("commit failed");

        // Verify that the new accounts caused even more pages to get added, this time at snapshot
        // 2
        let old_page_ids = page_ids;
        let new_page_ids = alive_page_ids(&db);
        assert!(
            new_page_ids.len() > old_page_ids.len(),
            "number of pages did not increase: {} -> {}",
            old_page_ids.len(),
            new_page_ids.len()
        );
        for page_id in &new_page_ids {
            let page = db
                .storage_engine
                .page_manager
                .get(1, *page_id)
                .unwrap_or_else(|err| panic!("page {page_id} not found: {err:?}"));
            if old_page_ids.contains(page_id) {
                assert_eq!(page.snapshot_id(), 1);
            } else {
                assert_eq!(page.snapshot_id(), 2);
            }
        }

        // Obtain a read transaction, and verify that it can access all the initial accounts
        let mut read_tx = db.begin_ro().expect("ro transaction creation failed");
        for (address, account) in &initial_accounts {
            assert_eq!(
                read_tx.get_account(address).expect("error while reading account"),
                account.clone()
            );
        }

        // Delete the initial accounts
        let mut tx = db.begin_rw().expect("rw transaction creation failed");
        for (address, _) in &initial_accounts {
            tx.set_account(address.clone(), None).expect("deleting account failed");
        }
        tx.commit().expect("commit failed");

        // Verify that the read transaction that we created before the delete can still access the
        // initial accounts
        read_tx.clear_cache();
        for (address, account) in &initial_accounts {
            assert_eq!(
                read_tx.get_account(address).expect("error while reading account"),
                account.clone()
            );
        }
    }

    #[test]
    fn test_db_arc_tx() {
        let tmp_dir = TempDir::new("test_db").unwrap();
        let file_path = tmp_dir.path().join("test.db");
        let db = Database::create_new(&file_path).unwrap();

        let db_arc = Arc::new(db);

        let address = address!("0xd8da6bf26964af9d7eed9e03e53415d37aa96045");
        let mut tx = begin_rw(db_arc.clone()).unwrap();
        tx.set_account(
            AddressPath::for_address(address),
            Some(Account::new(1, U256::from(100), EMPTY_ROOT_HASH, KECCAK_EMPTY)),
        )
        .unwrap();
        tx.commit().unwrap();

        let mut tx = begin_ro(db_arc).unwrap();
        let account = tx.get_account(&AddressPath::for_address(address)).unwrap().unwrap();
        assert_eq!(account, Account::new(1, U256::from(100), EMPTY_ROOT_HASH, KECCAK_EMPTY));
    }
}
